#https://github.com/rongfengliang/clickhouse-docker-compose
version: "3"
services:
  clickhouse-server:
    image: yandex/clickhouse-server
    labels:
      NAME: "database-server"
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./database/database/ch_data:/var/lib/database/
      - ./database/database/ch_logs:/var/log/database-server/
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  clickhouse-client:
    image: yandex/clickhouse-client
    labels:
      NAME: "database-client"
    command: ['--host', 'server']

  rabbit1:
    image: rabbitmq:3-management
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RABBITCOOKIE"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - ./rabbitmq/rabbitmq-node-1/data/:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq-node-1/log/:/var/log/rabbitmq