#https://github.com/rongfengliang/clickhouse-docker-compose
version: "3"

networks:
  go-metr-network:

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    labels:
      NAME: "database-server"
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./database/database/ch_data:/var/lib/database/
      - ./database/database/ch_logs:/var/log/database-server/
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      go-metr-network:
  clickhouse-client:
    image: yandex/clickhouse-client
    labels:
      NAME: "database-client"
    command: ['--host', 'server']

  rabbit1:
    image: rabbitmq:3-management
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RABBITCOOKIE"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - ./rabbitmq/rabbitmq-node-1/data/:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq-node-1/log/:/var/log/rabbitmq
    networks:
      go-metr-network:

  rest-receiver:
    image: surkovvs/go-metr-receiver:latest
    hostname: "receiver1"
    environment:
      APP_PORT: "3000"
    ports:
      - "3000:3000"
    labels:
      NAME: "receiver1"
    volumes:
      - ./rest-receiver/:/usr/local/bin/config/
    restart: unless-stopped
    depends_on:
      - clickhouse-server
      - rabbit1
    networks:
      go-metr-network:
    healthcheck:
      test: curl --fail -s http://localhost:3000/status || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: 128m

  clickhouse-sender:
    image: surkovvs/go-metr-sender:latest
    hostname: "receiver1"
    environment:
      APP_PORT: "4000"
    ports:
      - "4000:4000"
    labels:
      NAME: "receiver1"
    volumes:
      - ./clickhouse-sender:/usr/local/bin/config/
    restart: unless-stopped
    depends_on:
      - clickhouse-server
      - rabbit1
    networks:
      go-metr-network:
    healthcheck:
      test: curl --fail -s http://localhost:4000/status || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: 128m
