#https://github.com/rongfengliang/clickhouse-docker-compose
version: "3"
services:
  server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - $HOME/github/go-metr/db/ch_data:/var/lib/clickhouse/
      - $HOME/github/go-metr/db/ch_logs:/var/log/clickhouse-server/

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  client:
    image: yandex/clickhouse-client
    command: ['--host', 'server']

