server:
  port: 4000
  name: rncb
  full_name: clickhouse-sender-DEV
  log_level: 1
  pretty_log: true
  http_logging: false
  enable_profiling: false
  enable_request_id: false

rabbitmq:
  host: localhost
  port: 5672
  user: rabbitmq
  password: rabbitmq
  exchange: exchange
  exchange_type: direct
  binding_key: key
  consumer_tag: consumer
  batch_max_items: 2000
  batch_max_timeout_mills: 50

database:
  host: localhost
  port: 9000
  default_database: default
  user: default
  password: ""
  debug: false
  dial_timeout: time.Second
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: time.Hour
  batch_max_items: 2000
  batch_max_timeout_mills: 50
